add_executable(vdf_test vdf/vdf_test.cpp)
target_link_libraries(vdf_test PRIVATE iideck::vdf)
add_test(NAME vdf COMMAND vdf_test)

add_subdirectory(config)
add_subdirectory(library)
add_subdirectory(artwork)
add_subdirectory(audio)
add_subdirectory(launch)
add_subdirectory(steam)
add_subdirectory(session)
add_subdirectory(device)
add_subdirectory(ui)
add_subdirectory(gamepad)
add_subdirectory(app)
