add_executable(pad_translator_test pad_translator_test.cpp)
target_link_libraries(pad_translator_test PRIVATE iideck::pad)
target_include_directories(pad_translator_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../ui")
target_compile_options(pad_translator_test PRIVATE -Wall -Wextra -Wpedantic)
add_test(NAME pad_translator COMMAND pad_translator_test)

add_executable(pads_test pads_test.cpp)
target_link_libraries(pads_test PRIVATE iideck::pad)
target_include_directories(pads_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../ui")
target_compile_options(pads_test PRIVATE -Wall -Wextra -Wpedantic)
add_test(NAME pads COMMAND pads_test)
set_tests_properties(pads PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 30)

add_executable(direction_repeat_test direction_repeat_test.cpp)
target_link_libraries(direction_repeat_test PRIVATE iideck::pad)
target_include_directories(direction_repeat_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../ui")
target_compile_options(direction_repeat_test PRIVATE -Wall -Wextra -Wpedantic)
add_test(NAME direction_repeat COMMAND direction_repeat_test)
